// @ts-nocheck

/*
 * MIT License
 * 
 * Copyright (c) 2026 Pelemenguin
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * EnumJS is a KubeJS JavaScript library for creating Java enum classes.
 * 
 * ## Usage
 * 
 * Use the {@linkcode createEnum} method to create a new Java `enum`.
 * 
 * > ```javascript
 * > let colors = EnumJS.createEnum("Color")
 * >     .build("RED", "GREEN", "BLUE");
 * > ```
 * 
 * The return value of `createEnum` is a Java class.
 * You can directly access the static methods of this Java class via `colors`:
 * 
 * > ```javascript
 * > colors.GREEN;          // Get the GREEN enum instance
 * > colors.valueOf("RED"); // Get the RED enum instance
 * > colors.values();       // Get an array of all enum instances
 * > ```
 * 
 * ## Type Definitions
 * 
 * Since both ProbeJS 6 and ProbeJS 7 exist on Minecraft 1.20.1,
 * the type definition files they generate are vastly different.
 * To get correct type hints, go to the {@linkcode Alias} namespace and change the aliases to match your own ProbeJS-generated type definitions.
 * 
 * Additionally, this module provides multi-language `.d.ts` files.
 * When using it, configure `jsconfig.json` to ignore files of other languages, or simply delete the ones you don't need.
 * 
 * ## KubeLoader
 * 
 * This module supports loading via KubeLoader.
 * When using KubeLoader, use:
 * 
 * > ```javascript
 * > const EnumJS = ContentPacks.getShared("pelemenguin.enumjs");
 * > // or more strictly:
 * > const EnumJS = ContentPacks.getShared("startup", "pelemenguin.enumjs");
 * > ```
 * 
 * to load it into your own script.
 * 
 * ---
 * 
 * @author Pelemenguin
 * @version 1.0
 * @license MIT
 * @copyright Pelemenguin 2026
 */
declare namespace EnumJS {

    /**
     * Predefined aliases for documentation.
     * 
     * If these do not match the files generated by ProbeJS,
     * you can change them here to ensure your documentation works correctly.
     */
    namespace Alias {

        /** `java.lang.Enum` */
        type Enum<E extends Enum<E>>   = Internal.Enum<E>;

    }

    /**
     * Creates a new Java enum class.
     * 
     * @param className The class name of the enum class (Full qualified name, e.g. `com.exmaple.ExampleEnum`)
     * 
     * @since 1.1: No longer directly accepts an array of enum instances to build the Java enum class.
     * 
     * @example
     * let ExampleEnum = EnumJS.createEnum("ExampleEnum")
     *     .build("Value1", "Value2", "Value3");
     * console.info(ExampleEnum.Value1);
     */
    function createEnum(className: string): EnumClassBuilder;

    /**
     * Builder for creating Java enum classes.
     * 
     * @since 1.1
     */
    class EnumClassBuilder {
        protected constructor(className: string);
        protected className: string;
        protected stringRepresentableCode?: ((methodVisitor: any) => void);
        protected customStringRepresentable?: (value: GeneratedEnum<string>) => void;
        /**
         * Builds the Java enum class.
         * 
         * @param values Names for the enum instances
         * @return       The built Java enum class
         * 
         * @since 1.1
         */
        build<A extends string>(...values: A[]): Enum<A>;
        /**
         * Makes the generated enum class implement the `net.minecraft.util.StringRepresentable` interface.
         * 
         * @param getter A function to get the string representation of the enum instance.
         *               When omitted, the enum instance's name will be used as its string representation by default
         * @return       The current builder instance
         * 
         * @since 1.1
         */
        stringRepresentable(getter: (value: GeneratedEnum<string>) => void): EnumClassBuilder;
    }

    /**
     * Type representing the generated Java enum class for type hints.
     * 
     * @since 1.1
     */
    type Enum<E extends string> = {[K in E]: GeneratedEnum<K>} & _Enum<E>;

    /**
     * Interface representing the generated Java enum class for type hints.
     */
    interface _Enum<E extends string> {
        /**
         * Gets the enum instance corresponding to the given name.
         * 
         * @param value The name of the enum instance
         * @return      The enum instance with the matching name
         */
        valueOf<S extends E>(value: S): GeneratedEnum<S>;
        /**
         * Returns an array containing all enum instances of this enum class.
         * 
         * @return Array of enum instances
         */
        values(): GeneratedEnum<E>[];
    }

    /**
     * Interface representing an enum instance for type hints.
     * 
     * @since 1.1: 添加了一个泛型参数来表示当前枚举实例的名称
     */
    interface GeneratedEnum<E extends string> extends Alias.Enum<GeneratedEnum<E>> {
        name(): E;
    }

}
