// @ts-nocheck

/*
 * MIT License
 * 
 * Copyright (c) 2026 Pelemenguin
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * EnumJS is a KubeJS JavaScript library for creating Java enum classes.
 * 
 * ## Usage
 * 
 * Use the {@linkcode createEnum} method to create a new Java `enum`.
 * 
 * > ```javascript
 * > let colors = EnumJS.createEnum("Color", ["RED", "GREEN", "BLUE"]);
 * > ```
 * 
 * The return value of `createEnum` is a Java class.
 * You can directly access the static methods of this Java class via `colors`:
 * 
 * > ```javascript
 * > colors.valueOf("RED"); // Get the RED enum instance
 * > 
 * > colors.values();       // Get an array of all enum instances
 * > ```
 * 
 * ## Type Definitions
 * 
 * Since both ProbeJS 6 and ProbeJS 7 exist on Minecraft 1.20.1,
 * the type definition files they generate are vastly different.
 * To get correct type hints, go to the {@linkcode Alias} namespace and change the aliases to match your own ProbeJS-generated type definitions.
 * 
 * Additionally, this module provides multi-language `.d.ts` files.
 * When using it, configure `jsconfig.json` to ignore files of other languages, or simply delete the ones you don't need.
 * 
 * ## KubeLoader
 * 
 * This module supports loading via KubeLoader.
 * When using KubeLoader, use:
 * 
 * > ```javascript
 * > const EnumJS = ContentPacks.getShared("pelemenguin.enumjs");
 * > // or more strictly:
 * > const EnumJS = ContentPacks.getShared("startup", "pelemenguin.enumjs");
 * > ```
 * 
 * to load it into your own script.
 * 
 * ---
 * 
 * @author Pelemenguin
 * @version 1.0
 * @license MIT
 * @copyright Pelemenguin 2026
 */
declare namespace EnumJS {

    /**
     * Predefined aliases for documentation.
     * 
     * If these do not match the files generated by ProbeJS,
     * you can change them here to ensure your documentation works correctly.
     */
    namespace Alias {

        /** `java.lang.Enum` */
        type Enum<E extends Enum<E>>   = Internal.Enum<E>;

    }

    function createEnum(className: string): EnumClassBuilder;

    class EnumClassBuilder {
        protected constructor(className: string);
        protected className: string;
        build<A extends string>(...values: A[]): Enum<A>;
    }

    /**
     * Interface representing the generated Java enum class for type hints.
     */
    interface Enum<E extends string> {
        /**
         * Gets the enum instance corresponding to the given name.
         * 
         * @param value The name of the enum instance
         * @return      The enum instance with the matching name
         */
        valueOf(value: E): GeneratedEnum;
        /**
         * Returns an array containing all enum instances of this enum class.
         * 
         * @return Array of enum instances
         */
        values(): GeneratedEnum[];
    }

    /**
     * Interface representing an enum instance for type hints.
     */
    interface GeneratedEnum extends Alias.Enum<GeneratedEnum> {}

}
