// @ts-nocheck

namespace ComponentStylizer {

    /**
     * Pre-defined aliases for documentation.
     * 
     * If these do not match your own typings generated by ProbeJS,
     * you can modify them to match your own typings to make sure the documentation is correct.
     */
    namespace Alias {

        /** `net.minecraft.ChatFormatting` */
        type  ChatFormatting =        Internal.ChatFormatting;
        type $ChatFormatting = typeof Internal.ChatFormatting;
        /** `net.minecraft.network.chat.Component` */
        type Component       =        net.minecraft.network.chat.Component;
        /** `net.minecraft.network.chat.Style` */
        type  Style          =        Internal.Style;
        type $Style          = typeof Internal.Style;

    }

    /**
     * `LazyComponent` handles the invocation of {@linkcode Stylizer.transform}.
     * 
     * The `transform` method involves text parsing and its implementation may vary across different `Stylizer` subclasses.
     * Therefore, the `transform` method can be time-consuming and may cause lag in high-frequency call scenarios.
     * 
     * `LazyComponent` caches and reuses the `Component` produced by the `Stylizer`,
     * avoiding performance waste from repeated transformations.
     * 
     * However, `LazyComponent` refreshes its cache when the **text of the `Component` changes**.
     * This is designed to account for players switching game languages.
     * Hence, `LazyComponent` is not very effective for `Component`s whose text changes frequently.
     * 
     * ## Usage
     * 
     * `LazyComponent` can be created via its constructor or the {@linkcode of} method:
     * 
     * > ```javascript
     * > let emphasizer = ComponentStylizer.Emphasizer.create();
     * > let lazy = ComponentStylizer.LazyComponent.of(Component.literal("This is a _emph_ test!"), emphasizer);
     * > // or
     * > // let lazy = new ComponentStylizer.LazyComponent(Component.literal("..."), emphasizer);
     * > ```
     * 
     * To obtain the transformed `Component`, use the {@linkcode get} method:
     * 
     * > ```javascript
     * > let component = lazy.get();
     * > if (Client.player) {
     * >     Client.player.tell(component);
     * > }
     * > ```
     * 
     * To refresh the cache, use {@linkcode clearCache} to discard the previously obtained result,
     * so that the next `get` call recomputes it.
     * 
     * Alternatively, use {@linkcode refreshAndGet}, which also clears the cache
     * but recomputes immediately and returns the result, rather than waiting for the next `get` call.
     * 
     * > ```javascript
     * > lazy.clearCache();
     * > lazy.get();           // recomputes here
     * > 
     * > lazy.refreshAndGet(); // recomputes immediately
     * > ````
     */
    class LazyComponent {
        /**
         * Constructs a new `LazyComponent`.
         * 
         * @param component The `Component` to transform
         * @param stylizer  The `Stylizer` to use
         */
        constructor(component: Alias.Component, stylizer: Stylizer);
        protected cachedString: string;
        protected cachedResult: Alias.Component;
        protected rawComponent: Alias.Component;
        protected stylizer: Stylizer;
        /**
         * Creates a new `LazyComponent`.
         * 
         * @param component The `Component` to transform
         * @param stylizer  The `Stylizer` to use
         * @returns         The created `LazyComponent`
         */
        static of(component: Alias.Component, stylizer: Stylizer): LazyComponent;
        /**
         * Gets the transformed result.
         * 
         * @returns The result
         */
        get(): Alias.Component;
        /**
         * Clears the cache without immediate recomputation.
         */
        clearCache(): void;
        /**
         * Clears the cache and immediately recomputes the result.
         * 
         * @returns The transformed result
         */
        refreshAndGet(): Alias.Component;
    }

    /**
     * `Stylizer` is an abstract base class that specifies a `transform` method used to convert a string into a `Component` with a custom style.
     */
    abstract class Stylizer {
        /**
         * Transforms the given text.
         * 
         * @param text The input text
         */
        abstract transform(text: string): Alias.Component;
        /**
         * Creates a {@linkcode LazyComponent} of `Component.literal(text)` using this `Stylizer`.
         * 
         * @param text The input text
         * @returns    The created `LazyComponent`
         */
        literal(text: string): LazyComponent;
        /**
         * Creates a {@linkcode LazyComponent} of `Component.translatable(key, objects)` using this `Stylizer`.
         * 
         * @param key     The translation key
         * @param objects The objects to format into the translation string
         * @returns       The created `LazyComponent`
         */
        translatable(key: string, ...objects: any[]): LazyComponent;
    }

    /**
     * A very simple `Stylizer` that has only 2 styles.
     * 
     * An `Emphasizer` emphasizes texts between `emphCharacter`s (defaulted to `_`) with `emphStyle`,
     * and the rest of the text is styled with `defaultStyle`.
     * 
     * For example:
     * 
     * |Original text       |Transformed text    |
     * |--------------------|--------------------|
     * |`plain text`        |plain text          |
     * |`_emphasized_ text` |**emphasized** text |
     * |`_1_ 2 _3_`         |**1** 2 **3**       |
     * |`golden\_apple`     |golden_apple        |
     * 
     * ## Usage
     * 
     * Use the constructor or the `create` method to create an `Emphasizer`.
     * 
     * > ```javascript
     * > // An default Emphasizer
     * > let emphasizer1 = new ComponentStylizer.Emphasizer();
     * > 
     * > // Another default Emphasizer
     * > let emphasizer2 = ComponentStylizer.Emphasizer.create();
     * > 
     * > // An Emphasizer with a specified emphStyle
     * > let emphasizer3 = ComponentStylizer.Emphasizer.create(
     * >     ComponentStylizer.Style.EMPTY.withBold(true).applyFormat("red")
     * > );
     * > 
     * > // An Emphasizer with emphStyle and defaultStyle both set
     * > let emphasizer4 = ComponentStylizer.Emphasizer.create(
     * >     ComponentStylizer.Style.EMPTY.withItalic(true).applyFormat("green"),
     * >     ComponentStylizer.Style.EMPTY.applyFormat("gray")
     * > );
     * > ```
     */
    class Emphasizer extends Stylizer {
        /**
         * Constructs a new `Emphasizer`.
         */
        constructor();
        protected defaultStyle: Alias.Style;
        protected emphStyle: Alias.Style;
        protected emphCharacter: string;
        static create(emphStyle?: Alias.Style, defaultStyle?: Alias.Style): Emphasizer;
        /**
         * Sets the style used for emphasized text.
         * 
         * @param style The style to set
         * @returns `this`
         */
        setEmphStyle(style: Alias.Style): this;
        /**
         * Sets the style used for default text.
         * 
         * @param style The style to set
         * @returns `this`
         */
        setDefaultStyle(style: Alias.Style): this;
    }

    /**
     * Pre-loaded Java class `net.minecraft.network.chat.Style`, provided for convenience.
     * 
     * ## Usage
     * 
     * To create a `Style` object, you can start with `ComponentStylizer.Style.EMPTY` and then use the `withXxx()` methods to modify it.
     * 
     * > ```javascript
     * > // Creates a bold blue style.
     * > ComponentStylizer.Style.EMPTY
     * >     .withBold(true)
     * >     .applyFormat("red")
     * > ```
     * 
     * Note that `Style`s are **immutable**, any `withXxx()` method will return a new `Style` object instead of modifying the original one.
     */
    const Style: Alias.$Style;

    /**
     * Pre-loaded Java class `net.minecraft.ChatFormatting`, provided for convenience.
     * 
     * ## Usage
     * 
     * `ChatFormatting` is an `enum`, used in Minecraft to represent text formatting options such as colors and styles.
     * 
     * Here are some examples:
     * 
     * > ```javascript
     * > // Colors
     * > ComponentStylizer.ChatFormatting.RED;
     * > ComponentStylizer.ChatFormatting.GREEN;
     * > ComponentStylizer.ChatFormatting.BLUE;
     * > ComponentStylizer.ChatFormatting.LIGHT_PURPLE;
     * > 
     * > // Other formats
     * > ComponentStylizer.ChatFormatting.BOLD;
     * > ComponentStylizer.ChatFormatting.ITALIC;
     * > ComponentStylizer.ChatFormatting.UNDERLINE;
     * > ```
     * 
     * Since `ChatFormatting` is an enum class, sometimes you can directly use strings instead of directly accessing static fields,
     * and Rhino can help you convert them.
     * 
     * > ```javascript
     * > ComponentStylizer.Style.EMPTY.applyFormat("red");
     * > ComponentStylizer.Style.EMPTY.applyFormat(ComponentStylizer.ChatFormatting.RED);
     * > ```
     */
    const ChatFormatting: Alias.$ChatFormatting;

}

declare const ComponentStylizer: ComponentStylizer;
