// @ts-nocheck
declare namespace Internal {

    /**
     * Internal namespace for `ComponentStylizer`.
     */
    namespace pelemenguin$ComponentStylizer {

        /**
         * Pre-defined aliases for documentation.
         * 
         * If these do not match your own typings generated by ProbeJS,
         * you can modify them to match your own typings to make sure the documentation is correct.
         */
        namespace Alias {

            /** `net.minecraft.network.chat.Component` */
            type Component = net.minecraft.network.chat.Component;
            /** `net.minecraft.network.chat.Style` */
            type Style = Internal.Style;

        }

        /**
         * A very simple Stylizer that has only 2 styles.
         * 
         * An `Emphasizer` emphasizes texts between `emphCharacter`s (defaulted to `_`) with `emphStyle`,
         * and the rest of the text is styled with `defaultStyle`.
         * 
         * For example:
         * 
         * |Original text       |Transformed text    |
         * |--------------------|--------------------|
         * |`plain text`        |plain text          |
         * |`_emphasized_ text` |**emphasized** text |
         * |`_1_ 2 _3_`         |**1** 2 **3**       |
         */
        class Emphasizer {
            constructor();
            private defaultStyle: Alias.Style;
            private emphStyle: Alias.Style;
            private emphCharacter: string;
            /**
             * Transforms a component
             * - - - - -
             * @param input The input `Component`
             * @returns     The transformed `Component`
             */
            transform(input: Alias.Component): Alias.Component;
        }

    }

}

declare interface ComponentStylizer {
    /**
     * A very simple Stylizer that has only 2 styles.
     * 
     * An `Emphasizer` emphasizes texts between `emphCharacter`s (defaulted to `_`) with `emphStyle`,
     * and the rest of the text is styled with `defaultStyle`.
     * 
     * For example:
     * 
     * |Original text       |Transformed text    |
     * |--------------------|--------------------|
     * |`plain text`        |plain text          |
     * |`_emphasized_ text` |**emphasized** text |
     * |`_1_ 2 _3_`         |**1** 2 **3**       |
     */
    Emphasizer: typeof Internal.pelemenguin$ComponentStylizer.Emphasizer;
}