// @ts-nocheck

declare namespace ComponentStylizer {

    /**
     * Pre-defined aliases for documentation.
     * 
     * If these do not match your own typings generated by ProbeJS,
     * you can modify them to match your own typings to make sure the documentation is correct.
     */
    namespace Alias {

        /** `net.minecraft.ChatFormatting` */
        type  ChatFormatting =        Internal.ChatFormatting;
        type $ChatFormatting = typeof Internal.ChatFormatting;
        /** `net.minecraft.network.chat.Component` */
        type Component       =        net.minecraft.network.chat.Component;
        /** `net.minecraft.network.chat.Style` */
        type  Style          =        Internal.Style;
        type $Style          = typeof Internal.Style;

    }

    /**
     * `Stylizer` is an abstract base class that specifies a `transform` method used to convert a string into a `Component` with a custom style.
     */
    abstract class Stylizer {
        /**
         * Transforms the given text.
         * 
         * @param text The input text
         */
        abstract transform(text: string): Alias.Component;
    }

    /**
     * A very simple `Stylizer` that has only 2 styles.
     * 
     * An `Emphasizer` emphasizes texts between `emphCharacter`s (defaulted to `_`) with `emphStyle`,
     * and the rest of the text is styled with `defaultStyle`.
     * 
     * For example:
     * 
     * |Original text       |Transformed text    |
     * |--------------------|--------------------|
     * |`plain text`        |plain text          |
     * |`_emphasized_ text` |**emphasized** text |
     * |`_1_ 2 _3_`         |**1** 2 **3**       |
     * |`golden\_apple`     |golden_apple        |
     * 
     * ## Usage
     * 
     * Use the constructor or the `create` method to create an `Emphasizer`.
     * 
     * ```javascript
     * // An default Emphasizer
     * let emphasizer1 = new ComponentStylizer.Emphasizer();
     * 
     * // Another default Emphasizer
     * let emphasizer2 = ComponentStylizer.Emphasizer.create();
     * 
     * // An Emphasizer with a specified emphStyle
     * let emphasizer3 = ComponentStylizer.Emphasizer.create(
     *     ComponentStylizer.Style.EMPTY.withBold(true).applyFormat("red")
     * );
     * 
     * // An Emphasizer with emphStyle and defaultStyle both set
     * let emphasizer4 = ComponentStylizer.Emphasizer.create(
     *     ComponentStylizer.Style.EMPTY.withItalic(true).applyFormat("green"),
     *     ComponentStylizer.Style.EMPTY.applyFormat("gray")
     * );
     * ```
     */
    class Emphasizer extends Stylizer {
        /**
         * Constructs a new `Emphasizer`.
         */
        constructor();
        protected defaultStyle: Alias.Style;
        protected emphStyle: Alias.Style;
        protected emphCharacter: string;
        static create(emphStyle?: Alias.Style, defaultStyle?: Alias.Style): Emphasizer;
        /**
         * Sets the style used for emphasized text.
         * 
         * @param style The style to set
         * @returns `this`
         */
        setEmphStyle(style: Alias.Style): this;
        /**
         * Sets the style used for default text.
         * 
         * @param style The style to set
         * @returns `this`
         */
        setDefaultStyle(style: Alias.Style): this;
    }

    /**
     * Pre-loaded Java class `net.minecraft.network.chat.Style`, provided for convenience.
     * 
     * ## Usage
     * 
     * To create a `Style` object, you can start with `ComponentStylizer.Style.EMPTY` and then use the `withXxx()` methods to modify it.
     * 
     * ```javascript
     * // Creates a bold blue style.
     * ComponentStylizer.Style.EMPTY
     *     .withBold(true)
     *     .applyFormat("red")
     * ```
     * 
     * Note that `Style`s are **immutable**, any `withXxx()` method will return a new `Style` object instead of modifying the original one.
     */
    const Style: Alias.$Style;

    /**
     * Pre-loaded Java class `net.minecraft.ChatFormatting`, provided for convenience.
     * 
     * ## Usage
     * 
     * `ChatFormatting` is an `enum`, used in Minecraft to represent text formatting options such as colors and styles.
     * 
     * Here are some examples:
     * 
     * ```javascript
     * // Colors
     * ComponentStylizer.ChatFormatting.RED;
     * ComponentStylizer.ChatFormatting.GREEN;
     * ComponentStylizer.ChatFormatting.BLUE;
     * ComponentStylizer.ChatFormatting.LIGHT_PURPLE;
     * 
     * // Other formats
     * ComponentStylizer.ChatFormatting.BOLD;
     * ComponentStylizer.ChatFormatting.ITALIC;
     * ComponentStylizer.ChatFormatting.UNDERLINE;
     * ```
     * 
     * Since `ChatFormatting` is an enum class, sometimes you can directly use strings instead of directly accessing static fields,
     * and Rhino can help you convert them.
     * 
     * ```java
     * ComponentStylizer.Style.EMPTY.applyFormat("red");
     * ComponentStylizer.Style.EMPTY.applyFormat(ComponentStylizer.ChatFormatting.RED);
     * ```
     */
    const ChatFormatting: Alias.$ChatFormatting;

}
