// @ts-nocheck

/*
 * MIT License
 * 
 * Copyright (c) 2026 Pelemenguin
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * MultiThreadic is a KubeJS JavaScript library that allows creating new threads and executing asynchronous tasks within KubeJS.
 * 
 * ## Usage
 * 
 * ### Creating Threads
 * 
 * > ```javascript
 * >                                   // thread name
 * > let thread = MultiThreadic.newThread("helloThread", () => {
 * >         // Terminate when the thread is interrupted,
 * >         // otherwise MultiThreadic cannot stop your created thread
 * >     while (!MultiThreadic.isInterrupted()) {
 * >         console.info("Hello! From another thread");
 * >     }
 * > });
 * > 
 * >  // When a thread with the same name already exists, newThread will not create a new thread,
 * >  // but returns null instead,
 * >  // common during script hot-reloading
 * > if (thread != null) {
 * >     thread.start();
 * > }
 * > ```
 * 
 * @see {@linkcode newThread}
 * 
 * ### Wrapping Tasks
 * 
 * When executing a function, the Rhino engine uses the **same context** as the current thread.
 * Since a Rhino context object can only be used by one thread at a time,
 * if you directly pass a function as `Callable` or `Runnable` to Java for execution,
 * even though they indeed run on another thread,
 * in reality these tasks will block the current thread until completion.
 * 
 * MultiThreadic provides a `TaskWrapper` to wrap the required tasks:
 * 
 * > ```javascript
 * > let task = () => {
 * >     let sum = 0;
 * >     for (let i = 0; i < 10000; i++) {
 * >         sum += Math.sin(i);
 * >     }
 * >     return sum;
 * > };
 * > 
 * > // If you pass task directly to another thread
 * > // the main thread will actually be blocked until task completes
 * > 
 * > // Use TaskWrapper to wrap this function
 * > 
 * > let wrappedTask = new MultiThreadic.TaskWrapper(task);
 * > 
 * > // When other threads execute wrappedTask, it will no longer block directly
 * > ```
 * 
 * Most methods of MultiThreadic (such as `newThread`, methods in `Executors`, etc.) will automatically use `TaskWrapper` to wrap passed-in functions,
 * so you generally don't need to use `TaskWrapper` manually.
 * 
 * @see {@linkcode TaskWrapper}
 * 
 * ## Type Definitions
 * 
 * Since both ProbeJS 6 and ProbeJS 7 exist on Minecraft 1.20.1,
 * the format of their generated type definition files is quite different.
 * To obtain correct type hints, you can visit the {@linkcode Alias} namespace to change the aliases to match the type definitions generated by your own ProbeJS.
 * 
 * Additionally, this module provides multilingual `.d.ts` files.
 * When using, configure `jsconfig.json` to ignore files of other languages, or simply delete the ones you don't need.
 * 
 * ## KubeLoader
 * 
 * This module supports loading via KubeLoader.
 * When using KubeLoader, use:
 * 
 * > ```javascript
 * > const MultiThreadic = ContentPacks.getShared("pelemenguin.multithreadic");
 * > // Or more rigorously:
 * > const MultiThreadic = ContentPacks.getShared("startup", "pelemenguin.multithreadic");
 * > ```
 * 
 * to load it into your own scripts.
 * 
 * ---
 * 
 * @author Pelemenguin
 * @version 1.0
 * @license MIT
 * @copyright Pelemenguin 2026
 */
declare namespace MultiThreadic {

    /**
     * Predefined aliases for documentation.
     * 
     * If these do not match the files generated by ProbeJS,
     * you can modify them here to ensure your documentation works correctly.
     */
    namespace Alias {

        /** `java.lang.Runnable` */
        type Runnable                       = Internal.Runnable;
        /** `java.lang.Thread` */
        type Thread                         = Internal.Thread;
        /** `java.util.Collection` */
        type Collection<E>                  = Internal.Collection<E>;
        type Collection_<E>                 = Internal.Collection_<E>;
        /** `java.util.List` */
        type List<E>                        = Internal.List<E>;
        /** `java.util.Map` */
        type Map<K, V>                      = Internal.Map<K, V>;
        /** `java.util.concurrent.Callable` */
        type Callable<V>                    = Internal.Callable<V>;
        /** `java.util.concurrent.ConcurrentHashMap` */
        type ConcurrentHashMap<K, V>        = Internal.ConcurrentHashMap<K, V>;
        /** `java.util.concurrent.ExecutorService` */
        type ExecutorService                = Internal.ExecutorService;
        /** `java.util.concurrent.Future` */
        type Future<V>                      = Internal.Future<V>;
        /** `java.util.concurrent.ScheduledExecutorService` */
        type ScheduledExecutorService       = Internal.ScheduledExecutorService;
        /** `java.util.concurrent.ScheduledFuture` */
        type ScheduledFuture<V>             = Internal.ScheduledFuture<V>;
        /** `java.util.concurrent.ThreadFactory` */
        type ThreadFactory                  = Internal.ThreadFactory;
        /** `java.util.concurrent.TimeUnit` */
        type TimeUnit                       = Internal.TimeUnit;
        type TimeUnit_                      = Internal.TimeUnit_;
        /** `java.util.concurrent.atomic.AtomicInteger` */
        type  AtomicInteger                 = Internal.AtomicInteger;
        type $AtomicInteger          = typeof Internal.AtomicInteger;
        /** `java.util.concurrent.atomic.AtomicLong` */
        type  AtomicLong                    = Internal.AtomicLong;
        type $AtomicLong             = typeof Internal.AtomicLong;
        /** `java.util.concurrent.atomic.AtomicBoolean` */
        type  AtomicBoolean                 = Internal.AtomicBoolean;
        type $AtomicBoolean          = typeof Internal.AtomicBoolean;
        /** `java.util.concurrent.atomic.AtomicReference` */
        type  AtomicReference<V>            = Internal.AtomicReference<V>;
        type $AtomicReference        = typeof Internal.AtomicReference;
        /** `java.util.concurrent.atomic.AtomicIntegerArray` */
        type  AtomicIntegerArray            = Internal.AtomicIntegerArray;
        type $AtomicIntegerArray     = typeof Internal.AtomicIntegerArray;
        /** `java.util.concurrent.atomic.AtomicLongArray` */
        type  AtomicLongArray               = Internal.AtomicLongArray;
        type $AtomicLongArray        = typeof Internal.AtomicLongArray;
        /** `java.util.concurrent.atomic.AtomicReferenceArray` */
        type  AtomicReferenceArray<E>       = Internal.AtomicReferenceArray<E>;
        type $AtomicReferenceArray   = typeof Internal.AtomicReferenceArray;
        /** `java.util.concurrent.locks.ReentrantLock` */
        type  ReentrantLock                 = Internal.ReentrantLock;
        type $ReentrantLock          = typeof Internal.ReentrantLock;
        /** `java.util.concurrent.locks.ReentrantReadWriteLock` */
        type  ReentrantReadWriteLock        = Internal.ReentrantReadWriteLock;
        type $ReentrantReadWriteLock = typeof Internal.ReentrantReadWriteLock;
        /** `java.util.concurrent.locks.StampedLock` */
        type  StampedLock                   = Internal.StampedLock;
        type $StampedLock            = typeof Internal.StampedLock;
        /** `java.util.concurrent.locks.Condition` */
        type  Condition                     = Internal.Condition;
        /** `java.util.concurrent.BlockingQueue` */
        type BlockingQueue<E>               = Internal.BlockingQueue<E>;
        /** `java.util.concurrent.CountDownLatch` */
        type  CountDownLatch                = Internal.CountDownLatch;
        type $CountDownLatch         = typeof Internal.CountDownLatch;
        /** `java.util.concurrent.CyclicBarrier` */
        type  CyclicBarrier                 = Internal.CyclicBarrier;
        type $CyclicBarrier          = typeof Internal.CyclicBarrier;
        /** `java.util.concurrent.Exchanger` */
        type  Exchanger                     = Internal.Exchanger;
        type $Exchanger              = typeof Internal.Exchanger;
        /** `java.util.concurrent.Phaser` */
        type  Phaser                        = Internal.Phaser;
        type $Phaser                 = typeof Internal.Phaser;
        /** `java.util.concurrent.RejectedExecutionHandler` */
        type RejectedExecutionHandler       = Internal.RejectedExecutionHandler;
        /** `java.util.concurrent.Semaphore` */
        type  Semaphore                     = Internal.Semaphore;
        type $Semaphore              = typeof Internal.Semaphore;

        /** `dev.latvian.mods.rhino.Context` */
        type Context             = Internal.Context;
        /** `dev.latvian.mods.rhino.DefiningClassLoader` */
        type DefiningClassLoader = Internal.DefiningClassLoader;

    }

    /**
     * Configuration of the MultiThreadic module.
     * 
     * Configured in `MultiThreadic.js` within `startup_scripts`.
     */
    namespace CONFIG {
        /**
         * The key of a hidden property in `global` used to store MultiThreadic-related data.
         * 
         * The default value for this configuration is `"pelemenguin$multithreadic"`.
         */
        const PROPERTY_IN_GLOBAL: string;
        /**
         * The name prefix for all threads created by MultiThreadic.
         * 
         * The default value for this configuration is `"MultiThreadic-"`.
         */
        const THREAD_NAME_PREFIX: string;
    }

    /**
     * Wraps a function so that it does not directly block the current thread when executed by Java.
     * 
     * Note that `TaskWrapper` is actually a class implementing `Runnable` and `Callable`.
     * Do not try to execute the wrapped function by calling it as a JavaScript function.
     */
    class TaskWrapper<T> implements Alias.Runnable, Alias.Callable<T> {
        constructor(task: () => T);
        run(): void;
        call(): T;
    }

    /**
     * Checks whether the current thread has been interrupted, equivalent to `MultiThreadic.currentThread().isInterrupted()`.
     * 
     * @returns `true` if the current thread has been interrupted; otherwise `false`.
     */
    function isInterrupted(): boolean;
    /**
     * Returns the `Thread` object of the current thread.
     * 
     * @returns the `Thread` object of the current thread.
     */
    function currentThread(): Alias.Thread;
    /**
     * Creates a new thread to execute the specified task.
     * 
     * @param identifier thread name.
     * @param task       the task to execute on the thread.
     * @returns          if the thread is created successfully, returns the new `Thread` object; if a thread with the same name already exists, returns `null`.
     * 
     * @example
     * let thread = MultiThreadic.newThread("sinSumCalculator", () => {
     *     let sum = 0;
     *     for (let i = 0; i < 10000; i++) {
     *         sum += Math.sin(i);
     *     }
     *     return sum;
     * });
     * 
     * if (thread != null) {
     *     thread.start();
     * }
     */
    function newThread(identifier: string, task: () => void): Alias.Thread?;
    /**
     * Lists the names of all threads created by MultiThreadic.
     * 
     * @returns a list of names of threads created by MultiThreadic, without the {@linkcode CONFIG.THREAD_NAME_PREFIX} prefix.
     */
    function listThreads(): string[];
    /**
     * Gets a thread created by MultiThreadic.
     * 
     * @param identifier thread name
     * @returns          the `Thread` object if a thread with the specified name exists; otherwise `null`.
     */
    function getThread(identifier: string): Alias.Thread?;
    /**
     * Attempts to stop a thread created by MultiThreadic.
     * 
     * @param identifier       thread name
     * @param waitTimeInMillis the time to wait for the thread to terminate (in milliseconds)
     * @returns                `true` if the thread does not exist or was terminated successfully; `false` if it could not be terminated within the specified time.
     */
    function stopThread(identifier: string, waitTimeInMillis: number = 1000): boolean;
    /**
     * Attempts to stop a thread created by MultiThreadic, and after succeeding, creates a new thread to execute the specified task.
     * 
     * @param identifier       thread name
     * @param task             the task to execute on the thread
     * @param waitTimeInMillis the time to wait for the thread to terminate (in milliseconds)
     * @returns                if the thread does not exist or was terminated successfully, returns the new `Thread` object
     * @throws                 if a thread with the same name exists and cannot be terminated within the specified time, throws an error
     */
    function stopThenNewThread(identifier: string, task: () => void, waitTimeInMillis: number = 1000): Alias.Thread;
    /**
     * Causes the current thread to sleep for the specified duration.
     * 
     * @param millis the sleep time in milliseconds
     */
    function sleep(millis: number): void;

    /**
     * Executes a function; if two `synchronized` calls use the same object as the lock, the tasks are guaranteed not to execute simultaneously.
     * 
     * Here is a simple example:
     * 
     * > ```javascript
     * > let lock = {};
     * > let data = 0;
     * > 
     * > let someTask = (value) => {
     * >     // Protect the inner code so only one thread executes it at a time
     * >     MultiThreadic.synchronized(lock, () => {
     * >         let currentData = data;
     * >         console.info("Thread " + MultiThreadic.currentThread().getName() + " read data: " + currentData);
     * >         // Assume some time-consuming operation here
     * >         MultiThreadic.sleep(1000);
     * >         data = currentData + value;
     * >         console.info("Thread " + MultiThreadic.currentThread().getName() + " updated data to: " + data);
     * >     });
     * > };
     * > 
     * > MultiThreadic.stopThenNewThread("thread1", () => someTask(1)).start();
     * > MultiThreadic.stopThenNewThread("thread2", () => someTask(2)).start();
     * > ```
     * 
     * This ensures `data` is correctly updated to `3`.
     * Otherwise, it's possible that both threads read the initial value `0` simultaneously,
     * and then update `data` to `1` or `2` respectively.
     * 
     * @param lock any object used as a lock
     * @param task the task to execute
     * @returns    the return value of the task
     */
    function synchronized<V>(lock: object, task: () => V): V;

    /**
     * Factory methods for Java's built-in thread pools.
     */
    namespace Executors {
        /**
         * See the [Java API documentation](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/Executors.html#newFixedThreadPool(int)).
         * 
         * Creates a thread pool that reuses a fixed number of threads operating off a shared unbounded queue.
         * At any point, at most `nThreads` threads will be active processing tasks.
         * If additional tasks are submitted when all threads are active, they will wait in the queue until a thread is available.
         * If any thread terminates due to a failure during execution prior to shutdown, a new one will take its place if needed to execute subsequent tasks.
         * The threads in the pool will exist until it is explicitly shutdown.
         * 
         * @param identifier    thread pool name
         * @param nThreads      the number of threads in the pool (> 0)
         * @param threadFactory the factory for creating new threads. If not provided, the default thread factory is used.
         * @returns             the created thread pool. If a pool with the same name already exists, the existing one is returned.
         */
        function fixedThreadPool(identifier: string, nThreads: number, threadFactory?: (runnable: Alias.Runnable) => Alias.Thread): ExecutorServiceWrapper;
        /**
         * See the [Java API documentation](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/Executors.html#newCachedThreadPool()).
         * 
         * Creates a thread pool that creates new threads as needed, but will reuse previously constructed threads when they are available.
         * These pools will typically improve the performance of programs that execute many short-lived asynchronous tasks.
         * Calls to `execute` will reuse previously constructed threads if available.
         * If no existing thread is available, a new thread will be created and added to the pool.
         * Threads that have not been used for 60 seconds are terminated and removed from the cache.
         * Thus, a pool that remains idle for long enough will not consume any resources.
         * Note that pools with similar properties but different details (e.g., timeout parameters) may be created using the {@linkcode customThreadPool} function.
         * 
         * @param identifier    thread pool name
         * @param threadFactory the factory for creating new threads. If not provided, the default thread factory is used.
         * @returns             the created thread pool. If a pool with the same name already exists, the existing one is returned.
         */
        function cachedThreadPool(identifier: string, threadFactory?: (runnable: Alias.Runnable) => Alias.Thread): ExecutorServiceWrapper;
        /**
         * See the [Java API documentation](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/Executors.html#newScheduledThreadPool(int)).
         * 
         * Creates a thread pool that can schedule commands to run after a given delay, or to execute periodically.
         * 
         * @param identifier    thread pool name
         * @param corePoolSize  the number of threads to keep in the pool, even if they are idle (≥ 0)
         * @param threadFactory the factory for creating new threads. If not provided, the default thread factory is used.
         * @returns             the created thread pool. If a pool with the same name already exists, the existing one is returned.
         */
        function scheduledThreadPool(identifier: string, corePoolSize: number, threadFactory?: (runnable: Alias.Runnable) => Alias.Thread): ScheduledExecutorServiceWrapper;
        /**
         * See the [Java API documentation](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/Executors.html#newSingleThreadExecutor()).
         * 
         * Creates an Executor that uses a single worker thread operating off an unbounded queue.
         * (Note however that if this single thread terminates due to a failure during execution prior to shutdown, a new one will take its place if needed to execute subsequent tasks.)
         * Tasks are guaranteed to execute sequentially, and no more than one task will be active at any given time.
         * Unlike the otherwise equivalent `fixedThreadPool(1, threadFactory)`, the returned executor is guaranteed not to be reconfigurable to use additional threads.
         * 
         * @param identifier    thread pool name
         * @param threadFactory the factory for creating new threads. If not provided, the default thread factory is used.
         * @returns             the created thread pool. If a pool with the same name already exists, the existing one is returned.
         */
        function singleThreadExecutor(identifier: string, threadFactory?: (runnable: Alias.Runnable) => Alias.Thread): ExecutorServiceWrapper;
        /**
         * See the [Java API documentation](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/Executors.html#newSingleThreadExecutor()).
         * 
         * Creates a single-threaded executor that can schedule commands to run after a given delay, or to execute periodically.
         * (Note however that if this single thread terminates due to a failure during execution prior to shutdown, a new one will take its place if needed to execute subsequent tasks.)
         * Tasks are guaranteed to execute sequentially, and no more than one task will be active at any given time.
         * Unlike the otherwise equivalent `scheduledThreadPool(1, threadFactory)`, the returned executor is guaranteed not to be reconfigurable to use additional threads.
         * 
         * @param identifier    thread pool name
         * @param threadFactory the factory for creating new threads. If not provided, the default thread factory is used.
         * @returns             the created thread pool. If a pool with the same name already exists, the existing one is returned.
         */
        function singleThreadScheduledExecutor(identifier: string, threadFactory?: (runnable: Alias.Runnable) => Alias.Thread): ScheduledExecutorServiceWrapper;
        /**
         * Creates a custom thread pool.
         * 
         * @param identifier thread pool name
         * @param parameters thread pool parameters
         * @returns          the created thread pool. If a pool with the same name already exists, the existing one is returned.
         */
        function customThreadPool(identifier: string, parameters: Types.ThreadPoolParameters): ExecutorServiceWrapper;
        /**
         * See the [Java API documentation](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/Executors.html#newWorkStealingPool(int)).
         * 
         * Creates a thread pool that maintains enough threads to support the given parallelism level, and may use multiple queues to reduce contention.
         * The parallelism level corresponds to the maximum number of threads that are actively engaged in, or available to engage in, task processing.
         * The actual number of threads may grow and shrink dynamically.
         * A work-stealing pool makes no guarantees about the order in which submitted tasks are executed.
         * 
         * @param identifier  thread pool name
         * @param parallelism the parallelism level of the pool (≥ 1). If not provided, defaults to `Runtime.getRuntime().availableProcessors()`.
         * @returns           the created thread pool. If a pool with the same name already exists, the existing one is returned.
         */
        function workStealingPool(identifier: string, parallelism?: number): ExecutorServiceWrapper;
        /**
         * Retrieves the names of all thread pools created by MultiThreadic.
         * 
         * @returns a list of names of thread pools created by MultiThreadic.
         */
        function listExecutors(): string[];
        /**
         * Gets a thread pool created by MultiThreadic.
         * 
         * @param identifier thread pool name
         */
        function getExecutor(identifier: string): ExecutorServiceWrapper;
    }

    /**
     * Java's built-in atomic variable classes.
     * 
     * For detailed information on each atomic variable, see the [Java API documentation](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/atomic/package-summary.html).
     */
    namespace Atomic {
        const Integer: Alias.$AtomicInteger;
        const Long: Alias.$AtomicLong;
        const Boolean: Alias.$AtomicBoolean;
        const Reference: Alias.$AtomicReference;
        const IntegerArray: Alias.$AtomicIntegerArray;
        const LongArray: Alias.$AtomicLongArray;
        const ReferenceArray: Alias.$AtomicReferenceArray;
    }

    /**
     * Java's built-in lock and synchronization tool classes.
     * 
     * For detailed information on each lock, see the [Java API documentation](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/locks/package-summary.html).
     */
    namespace Locks {
        const ReentrantLock: Alias.$ReentrantLock;
        const ReentrantReadWriteLock: Alias.$ReentrantReadWriteLock;
        const StampedLock: Alias.$StampedLock;
        const Semaphore: Alias.$Semaphore;
        const CountDownLatch: Alias.$CountDownLatch;
        const CyclicBarrier: Alias.$CyclicBarrier;
        const Exchanger: Alias.$Exchanger;
        const Phaser: Alias.$Phaser;
    }

    /**
     * Wraps a Java `ExecutorService`.
     * When submitting tasks, functions are automatically wrapped with `TaskWrapper`, eliminating the need to manually use `TaskWrapper`.
     */
    class ExecutorServiceWrapper {
        constructor(executorService: Alias.ExecutorService);
        execute(task: () => void): void;
        submit<T>(task: () => T): Alias.Future<T>;
        submit<T>(task: () => void, result: T): Alias.Future<T>;
        invokeAny<T>(tasks: Alias.Collection<() => T>, timeout?: number, timeUnit?: Alias.TimeUnit_): T;
        invokeAll<T>(tasks: Alias.Collection<() => T>, timeout?: number, timeUnit?: Alias.TimeUnit_): Alias.List<Alias.Future<T>>;
        isShutdown(): boolean;
        isTerminated(): boolean;
        shutdown(): void;
        shutdownNow(): Alias.List<Alias.Runnable>;
        awaitTermination(timeout: number, unit: Alias.TimeUnit_): boolean;
        get terminated(): boolean;
        /**
         * Gets the wrapped `ExecutorService` object.
         * Unless you know exactly what you're doing, it is not recommended to use this object directly to execute tasks.
         */
        get _delegate(): Alias.ExecutorService;
    }

    /**
     * Wraps a Java `ScheduledExecutorService`.
     * When submitting tasks, functions are automatically wrapped with `TaskWrapper`, eliminating the need to manually use `TaskWrapper`.
     */
    class ScheduledExecutorServiceWrapper extends ExecutorServiceWrapper {
        constructor(scheduledExecutorService: Alias.ScheduledExecutorService);
        schedule<V>(task: () => V, delay: number, unit: Alias.TimeUnit_): Alias.ScheduledFuture<V>;
        scheduleAtFixedRate(task: () => void, initialDelay: number, period: number, unit: Alias.TimeUnit_): Alias.ScheduledFuture<null>;
        scheduleWithFixedDelay(task: () => void, initialDelay: number, delay: number, unit: Alias.TimeUnit_): Alias.ScheduledFuture<null>;
    }

    type theGlobal = {
        threads: Alias.ConcurrentHashMap<string, Alias.Thread>;
        executorServices: Alias.ConcurrentHashMap<string, ExecutorServiceWrapper>;
        classLoader: Alias.DefiningClassLoader;
    };

    namespace Types {
        type ThreadPoolParameters = {
            /**
             * Core thread count; threads are kept in the pool even if idle.
             */
            corePoolSize?: number;
            /**
             * Maximum number of threads.
             * When the number of threads in the pool reaches the core size and a new task is submitted while the work queue is full,
             * new threads will be created to handle tasks, up to this maximum.
             */
            maximumPoolSize?: number;
            /**
             * When the number of threads in the pool exceeds the core size, threads that have been idle for longer than this value are terminated and removed from the pool.
             */
            keepAliveTime?: number;
            /**
             * The time unit for `keepAliveTime`.
             */
            timeUnit?: Alias.TimeUnit_;
            /**
             * The work queue used to hold tasks before they are executed.
             */
            workQueue?: Alias.BlockingQueue<Alias.Runnable>;
            /**
             * The factory for creating new threads. If not provided, the default thread factory is used.
             */
            threadFactory?: (runnable: Alias.Runnable) => Alias.Thread;
            /**
             * The handler for tasks that are rejected when the pool reaches its maximum size and the work queue is full.
             */
            rejectedExecutionHandler?: Alias.RejectedExecutionHandler;
        };
    }

}
